UserAction
mimhle/employee-management pull request #15
Opened 2023-11-21 14:31 UTC by Tamnemng

2023-11-22 01:44 UTC, mimhle commented
build failed
tại sao lại sửa class của t

2023-11-22 01:45 UTC, mimhle commented
muốn tạo file mới thì khởi tạo một cái class khác rồi viết vô file

2023-11-22 01:46 UTC, mimhle commented
tại sao lại sửa class của thg duy

2023-11-22 09:00 UTC, Tamnemng commented
> tại sao lại sửa class của thg duy

=))) t copy code mới của nó ấy

2023-11-22 09:01 UTC, mimhle commented
làm sao làm m chỉ đc commit mấy file của m thôi

2023-11-22 09:02 UTC, Tamnemng commented
> làm sao làm m chỉ đc commit mấy file của m thôi

ok để gỡ file duy ra

2023-11-22 10:42 UTC, Tamnemng commented
ok r ấy
check đi
có gì t sửa trong hôm nay luôn

2023-11-22 10:43 UTC, mimhle commented
> làm sao làm m chỉ đc commit mấy file của m thôi

2023-11-22 10:44 UTC, Tamnemng commented
t close xong t commit lại đc k

2023-11-22 10:45 UTC, mimhle commented
tại sao phải close
làm vâyh có khác gì commit lên bth đâu

2023-11-22 10:50 UTC, Tamnemng commented
v sao h =))) t xóa cái reposi này đi clone lại r commit lên à

2023-11-22 10:50 UTC, mimhle commented
sửa lại cho nó như cũ là đc rồi

2023-11-22 10:52 UTC, Tamnemng commented
chỉ t với t k undo đc

2023-11-22 10:53 UTC, Tamnemng commented
m vô dis chỉ t cho lẹ haha

2023-11-22 10:53 UTC, mimhle commented
copy paste lại file đi

2023-11-22 11:19 UTC, mimhle commented
> làm sao làm m chỉ đc commit mấy file của m thôi

2023-11-22 11:20 UTC, mimhle commented on UserAction.h
> +	std::string strRole;
tên biến private sai quy cách

2023-11-22 11:20 UTC, mimhle commented on UserAction.h
>  };
thiếu tài liệu

2023-11-22 11:22 UTC, mimhle commented on UserAction.cpp
> +}
ko cần chức năng tăng cấp

2023-11-22 11:22 UTC, mimhle commented on UserAction.cpp
> +			{
chưa format code

2023-11-22 11:23 UTC, mimhle commented on UserAction.cpp
> +		int lineNum = 0;
tên biến local sai quy cách

2023-11-22 11:24 UTC, mimhle commented on UserAction.cpp
> +		std::vector<std::vector<std::string>> dataUser = userData.read();
tên biến local sai quy cách

2023-11-22 11:26 UTC, mimhle requested changes
coi lại cách đặt tên biến và format code

2023-11-23 02:14 UTC, mimhle commented on UserAction.cpp
> +		else {
chưa format

2023-11-23 02:15 UTC, mimhle commented on UserAction.cpp
> +	int intLine = 0;
sai quy cách đặt tên

2023-11-23 02:17 UTC, mimhle requested changes
coi lại cách đặt tên và tối ưu if else

2023-11-23 11:28 UTC, mimhle commented on UserAction.cpp
> +		int iLine = -1;
giải thích tại sao là bắt đầu từ -1

2023-11-23 11:29 UTC, mimhle commented on UserAction.cpp
> +		{
chưa format

2023-11-23 11:29 UTC, mimhle commented on UserAction.cpp
> +		{
chưa format

2023-11-23 11:30 UTC, mimhle commented on UserAction.cpp
> +		return strUsers;
lật if lại rồi tối giản

2023-11-23 11:32 UTC, mimhle requested changes
coi lại việc tối giản if else, format code và đem giá trị mặc định của tham số qua file .h

2023-11-23 13:08 UTC, merged